### ISSUE TITLE
Frameworks

### ISSUE THREAD

**Issue by IannothSlurgh** [Gondee/pMIR#1]
Ionic
-Combines Angular and Cordova.
-Angular is well supported
-Cordova allows using Angular without writing native code
-Smaller app size.

https://www.quora.com/What-is-the-difference-between-Cordova-and-Ionic
https://www.quora.com/Can-I-use-AngularJS-for-building-an-Android-native-app-without-using-PhoneGap-or-Cordova
https://medium.com/@sonnylazuardi/ionic-framework-hybrid-app-vs-react-native-4facdd93f690#.awu6bp2ny

React Native (Combine with Angular)
-Less well supported (also fewer examples)
-Is a view library (requires other libraries/frameworks for the Model and Controller of MVC)
-Lower memory usage during execution
-Appearance is well tailored to mobile

https://www.quora.com/Is-React-killing-Angular
http://smashingboxes.com/blog/choosing-a-front-end-framework-angular-ember-react

Personally, I think I'd vote for Ionic because its monolithic. One framework, all functionality needed. It also helps that there should be many more examples out on the interwebs.

**Comment by clement360** [comment]
I'm cool with that, I'm more familiar with it and already know it can
handle what what we need.

**Comment by Gondee** [comment]
I'm on board with that. I haven't used either so it will be a learning experience for me lol.

**Comment by abrines4** [comment]
I haven't work with it either but it sounds good to me
