### ISSUE TITLE
Module Loading

### ISSUE THREAD

**Issue by IannothSlurgh** [Gondee/pMIR#12]
It is common in most programming languages to divided implementations across multiple files. In JS this can be accomplished using module systems. Browserify, RequireJS, ES6 modules, etc are all different means of connecting JS files together.

My question is, how do you want to glue the JS files together? This is especially important for me since my coding will immediately hinge on this (a GUI which seeks to take advantage of external PLS and PCA libraries). Oh, and it is also another useful detail for the CDR.

**Comment by IannothSlurgh** [comment]
I think Browserify may be the way to go because it has a focus on npm and the Node.js module system.

**Comment by Gondee** [comment]
As far as I know we are still up in the air about how the app will be written correct? Once we have the tests on if using stock java for android gets the Bluetooth connection we will be able to decide this?
