### ISSUE TITLE
Chemometrics Needs

### ISSUE THREAD

**Issue by Gondee** [Gondee/pMIR#16]
Chemometric Needs:
-Make the number of latent vectors static (2 so that we get 2 axes for a 2D graph)
-Save the model in the file system (pca offers the export function to produce an object which we can put in a JSON file or the like)
-Load the model from the file system
-Store/Load scan files

SIde note: what is in a training scan file
-the absorbances
-the concentrations (must know for data to have value)
-Perhaps a qualitative name (useful for PCA, but not essential)
-tags indicating the name of each material in the sample
Example:
"Bad Substance",[0.5, 0.5], [Evil A, Evil B], [3.3, 5.4, 9.1............]

**Comment by IannothSlurgh** [comment]
Accomplished
-Rudimentary load model done
-Rudimentary store/load scan files done

To Do
-make PCACompress available to get points for chart
-make measured available to get last point for chart
-verify functionality of pca/database (the big one)

**Comment by IannothSlurgh** [comment]
I have determined that an entire column of zeroes produces the weird NaNs.

**Comment by Gondee** [comment]
Damn. I have full load save unpushed. Ring dunks tonight, so I'll push tomorrow
