### ISSUE TITLE
Final: GUI Capabilities 

### ISSUE THREAD

**Issue by Gondee** [Gondee/pMIR#21]
- Graph PLS

- Graph PCA 

- Graph Absorbance

**Comment by IannothSlurgh** [comment]
Graph PCA complete
Graph Absorbance complete

**Comment by IannothSlurgh** [comment]
Josh, there is currently a bug in the GUI where putting in 100% for a concentration in the postscan screen will cause failure. This is why we input 99 during the demonstration for Gutierrez.

**Comment by Gondee** [comment]
Fixing @IannothSlurgh

**Comment by IannothSlurgh** [comment]
Completed long ago.
