### ISSUE TITLE
Chemometric Libraries

### ISSUE THREAD

**Issue by IannothSlurgh** [Gondee/pMIR#6]
We need JavaScript PLS and PCA libraries, preferably with few dependencies.

Machine Learning JS
https://github.com/mljs/pls
https://github.com/mljs/pca

Back-up PCA
https://bl.ocks.org/ktaneishi/9499896

**Comment by Gondee** [comment]
Found you some simulation data from TI
http://www.ti.com/tool/tida-00554

**Comment by IannothSlurgh** [comment]
I have determined that PLS has a dependency ml-matrix (https://github.com/mljs/matrix) which requires   a node version > 2.0.0. Please keep this in mind as we proceed forward.

**Comment by IannothSlurgh** [comment]
We figured this out a long time ago
